//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::availabilities::Entity as Availabilities;
pub use super::notes::Entity as Notes;
pub use super::projects::Entity as Projects;
pub use super::users::Entity as Users;
